services:
    api:
        build: ./api
        volumes:
            - ./data:/app/data:r
            - ./out:/app/out:w
        environment:
            - PYTHONUNBUFFERED=1
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: 1
                          capabilities: [gpu]
